version: "3.0"
services:
  authentication:
    image: ghcr.io/sbk-cloud-services/authentication-microservice:latest
    build:
      context: .
    links:
      - database
    ports:
      - "127.0.0.1:8080:8080"

  database:
    image: mariadb:latest
    volumes:
      - database:/var/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: jNPkaSSfBJA8dd4p4z39Vs69e52PvgBE
      MYSQL_DATABASE: authentication
      MYSQL_USER: authentication
      MYSQL_PASSWORD: jNPkaSSfBJA8dd4p4z39Vs69e52PvgBE
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  database:
